version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: SPEAK_EVAL_DB
      POSTGRES_USER: speakeval
      POSTGRES_PASSWORD: 3Pd7jt2Tk
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

