spring:
  profiles:
    include:
      - db
      - app
      - security
      - azure
      - actuator
#server:
#  servlet:
#    context-path: "/api"

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG