spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/SPEAK_EVAL_DB}
    username: ${SPRING_DATASOURCE_USERNAME:speakeval}
    password: ${SPRING_DATASOURCE_PASSWORD:3Pd7jt2Tk}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        proc:
          param_null_passing: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: ${SPRING_JPA_SHOW_SQL:true}